// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzngqgpztdijesmzanvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6bmdxZ3B6dGRpamVzbXphbnZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMjU3NjMsImV4cCI6MjA3NDYwMTc2M30.72ubAiZ67qpY0CNmH2ewj-2wt_sPoXpYk2o1p0XjCPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});